### ISSUE TITLE
It could not be used in 11.0 (Intel Mac)

### ISSUE THREAD

**Issue by lclfy** [rA9stuff/LeetDown#15]

**Comment by rA9stuff** [comment]
It should be fixed with version 1.0.3.

**Comment by DaanDH12** [comment]
It still doesn't work! It says the file is damaged and asks if I want to move it to my bin

**Comment by rA9stuff** [comment]
Check the FAQ at readme
